#!/usr/bin/env python3
import sys
import os

# Get the actual path of the script, following any symlinks
SCRIPT_DIR = os.path.dirname(os.path.realpath(__file__))
MAIN_SCRIPT = os.path.join(SCRIPT_DIR, "main.py")

# Forward all arguments to main.py
os.execv(sys.executable, [sys.executable, MAIN_SCRIPT] + sys.argv[1:])

